Sprint 2
igor799/middle.messenger.praktikum.yandex pull request #2
Opened 2021-06-14 15:21 UTC by igor799

2021-06-16 09:22 UTC, nickchamel requested changes
Привет) В целом работа отличная! Все чисто и аккуратно. Молодец. Есть несколько комментариев по коду, ознакомься пожалуйста. Проект пока возвращаю.

2021-06-16 09:22 UTC, nickchamel commented on src/core/Block.ts
> +    this.eventBus = () => eventBus;
Нет нужны возвращать его из функции. Можно просто 
`this.eventBus = new EventBus();`

2021-06-16 09:22 UTC, nickchamel commented on src/core/Block.ts
> +    this.props = this._makePropsProxy({ ...props, __id: this._id });
А зачем id в пропсах? Он всеравно созлдается один раз в конструкторе и никогда не меняется за жизнь компонента

2021-06-16 09:22 UTC, nickchamel commented on src/core/Block.ts
> +
Тут removeEventListener забыл сделать

2021-06-16 09:22 UTC, nickchamel commented on src/core/HTTPTransport.ts
> +        isGet && !!data ? `${url}${queryStringify(data)}` : url,
Это можно убрать из метода request и перенести выше в get() а в request() уже передавать готовый урл.
Тогда тут будет `xhr.open(method, url)` а `const isGet = method === METHOD.GET;` вообще не нужен будет. Это лишняя логика тут

2021-06-16 09:22 UTC, nickchamel commented on src/core/HTTPTransport.ts
> +      if (method === METHOD.GET || !data) {
А тут останется просто !data

2021-06-16 09:22 UTC, nickchamel commented on src/utils/submitForm.ts
> +export function submitForm(element: HTMLFormElement) {
Старайся называть методы так, что читая его названия понятно что он делает. В данном случае это не обработчик который сабмитит форму, а хэлпер, который забирает данные с формы. То есть например getFormData

2021-06-16 09:22 UTC, nickchamel commented on index.html
> +<!DOCTYPE html>
Пара слов по поводу структуры проекта.
По заданию нужно было сделать папки pages и components. У тебя сейчас pages лежат вместе с components. Папки pages нет, но есть layouts. Я когда вижу layouts то ожидаю там темплейты) но не файлы со скриптами. По сути pages это те же components просто лежат отдельно. Внутри них могут быть вложенные компоненты, которые есть только на определенной странице, а в папке src/components лежат компоненты которые "шерятся" между страницами и другими компонентами. Ты можешь вынести компоненты страниц в свою папку и объединить скрипты с теми что лежат в layouts. Или ты можешь вынести скрипты из layouts в src. Layouts на примере pug - это то от чего ты экстендишь шаблоны (`extends ../layouts/main`). И я не понял почему ты удалил папку static. Ведь в любой момент могут появится какие-либо ассеты. Причем все страницы у тебя лежат в pages а логин в корне проекта.

2021-06-16 21:25 UTC, igor799 commented on package.json
> +    "start": "parcel build index.html ./pages/*.html && node ./index.ts",
Так сделать не получится. Не проходит тест: [check_parcel.sh](https://github.com/Yandex-Practicum/tests-second-floor/blob/master/sprint_1/check_parcel.sh).
Сделал так:
```
"dev": "parcel ./static/*.html --no-cache",
"build": "parcel build ./static/*.html",
"prestart": "parcel build ./static/*.html",
"start": "node ./index.ts",
```

2021-06-16 21:42 UTC, igor799 commented on src/components/Profile/Profile.ts
> +            }),
Создаю экземпляры внутри Block с помощью `_makeChildren`:
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/49136bdfe4bcfe5ff66bbd12042a894cfd9073a3/src/core/Block.ts#L166-L177

Так прокидываю children данные:
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/49136bdfe4bcfe5ff66bbd12042a894cfd9073a3/src/pages/Profile/Profile.ts#L30-L48

2021-06-16 21:44 UTC, igor799 commented on src/utils/submitForm.ts
> +export function submitForm(element: HTMLFormElement) {
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/49136bdfe4bcfe5ff66bbd12042a894cfd9073a3/src/utils/getFormData.ts#L1

2021-06-16 21:48 UTC, igor799 commented on src/core/Block.ts
> +
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/49136bdfe4bcfe5ff66bbd12042a894cfd9073a3/src/core/Block.ts#L90

2021-06-16 21:49 UTC, igor799 commented on index.html
> +<!DOCTYPE html>
Исправил структуру. Разбил на папки components, pages, static

2021-06-16 22:01 UTC, nickchamel approved these changes
Привет еще раз. Работу я принимаю. Отлично поработал. Я тебе еще просто оставил несколько комментариев как можно улучшить

2021-06-16 22:12 UTC, nickchamel commented on src/components/ContactPanel/ContactPanel.ts
> +  }
Ну и само собой реализация метода children в Block поменяется. В статику только надо будет добавить айдишники чтобы их различать

2021-06-17 12:49 UTC, igor799 commented on src/components/AuthForm/AuthForm.ts
> +  }
Вернул на тэг) Добавил константу
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/04baba217aa83640b3d8932ad1c76223202f9562/src/components/AuthForm/AuthForm.ts#L14-L16

2021-06-17 12:50 UTC, igor799 commented on src/components/AuthForm/AuthForm.ts
> +    }))();
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/04baba217aa83640b3d8932ad1c76223202f9562/src/components/AuthForm/AuthForm.ts#L61-L66

2021-06-17 12:54 UTC, igor799 commented on src/components/ContactPanel/ContactPanel.ts
> +  }
Вынес статику в mockData.ts:
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/04baba217aa83640b3d8932ad1c76223202f9562/src/components/ContactPanel/ContactPanel.ts#L6

https://github.com/igor799/middle.messenger.praktikum.yandex/blob/04baba217aa83640b3d8932ad1c76223202f9562/src/components/ContactPanel/ContactPanel.ts#L14

Поправил  _makeChildren:
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/04baba217aa83640b3d8932ad1c76223202f9562/src/core/Block.ts#L166-L175

2021-06-17 12:54 UTC, igor799 commented on src/utils/getFormData.ts
> +}
https://github.com/igor799/middle.messenger.praktikum.yandex/blob/04baba217aa83640b3d8932ad1c76223202f9562/src/utils/getFormData.ts#L1-L11

2021-06-18 17:36 UTC, merged